version: "3.8"

services:

  postgres:
    image: postgres:16-alpine
    container_name: evently-postgres
    environment:
      POSTGRES_DB: event_ticketing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./event-ticketing-system
    container_name: evently-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/event_ticketing_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: evently-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: